package com.ctn.offerwall.common.event;

public enum EventType {
    USER_SIGNED_UP,
    USER_LOGIN_SUCCEEDED,
    USER_LOGIN_FAILED,
    USER_UPDATED,
    USER_ROLE_GRANTED,
    USER_ROLE_REVOKED,

    WALLET_CARD_ADDED,
    WALLET_CARD_DELETED,

    CARD_CREATED,
    CARD_UPDATED,
    CARD_DELETED,
    CARD_MATCH_REQUESTED,

    OFFER_CREATED,
    OFFER_UPDATED,
    OFFER_DELETED,
    OFFER_CATEGORY_CREATED,
    OFFER_CATEGORY_UPDATED,
    OFFER_CATEGORY_DELETED,

    ELIGIBILITY_CHECKED,

    NOTIFICATION_CREATED,
    NOTIFICATION_QUEUED,
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED,

    ADMIN_ACTION_PERFORMED
}
