server:
  port: 8082

spring:
  application:
    name: offer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/offerwall_offer
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

offerwall:
  security:
    jwt:
      issuer: offerwall-user-service
      audience: offerwall-api
      require-signature: false
  tracking:
    enabled: true
    base-url: http://localhost:8084
    fail-on-error: false
  clients:
    user:
      base-url: http://localhost:8081
      internal-api-key:
    eligibility:
      base-url: http://localhost:8083
      internal-api-key:
