server:
  port: 8085

spring:
  application:
    name: card-service

  datasource:
    url: jdbc:postgresql://localhost:5433/offerwall_card
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
