server:
  port: 8085

spring:
  application:
    name: card-service

  datasource:
    url: jdbc:postgresql://localhost:5432/offerwall_card
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

offerwall:
  security:
    internal:
      api-key:
    jwt:
      issuer: offerwall-user-service
      audience: offerwall-api
      require-signature: false
